<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BO2InjectorGUI</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace>BO2InjectorGUI</RootNamespace>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);decompiled\**;pdb-decompiled\**;.tools\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="libdebug">
      <HintPath>libdebug.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="*.gscc" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
